appName: payment
replicaCount: 1
image:
  repository: 608320470413.dkr.ecr.us-east-1.amazonaws.com/payment
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
   create: true
   annotations: {}
   name: payment

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi       